### PR TITLE
GNATCuda: Automatic binding

### PR DESCRIPTION
**Pull request by leogermond**
With this change the CUDA bindings version is checked at startup and
the corresponding bindings are generated if it does not correspond to
the local informations.

At the moment the only version information is that of gnatvsn, which
is pretty limited.

$CUDA_ROOT should be specified so that the binding script works properly.
By default it uses /usr/local/cuda which is unfit for Windows.

### CODE REVIEW

**Comment by leogermond** [comment]
Having issues with build as the wrapper is used called bb-runtime prior to install, at which point the binding is not possible and not welcome either

**Comment by glacambre** [comment]
>the wrapper is called by bb-runtime prior to install

This sounds odd to be, bb-runtime shouldn't have any knowledge of the wrapper. Could you describe where/how you are seeing this?

**Comment by leogermond** [comment]
This is happening in build_rts.py which is itself called by Makefile. See this anod logs where cuda-gcc is being called
`cp wrapper/obj/gnatcuda_wrapper install/bin/cuda-gcc
cp install/bin/cuda-gcc /home/germond/Workspace/wave/x86_64-linux/gnat-llvm-ptx/install/bin/cuda-gcc
./gen-rts-sources.py --bb-dir ../bb-runtimes --gnat ../gnat --rts-profile=light
# Disable bindings because cuda_env is not installed at this point
CUDA_GCC_DISABLE_BINDINGS=1 ./build-rts.py --bb-dir ../bb-runtimes --rts-src-descriptor install/lib/gnat/rts-sources.json cuda-device --force -b
install runtime sources for cuda
building project /home/germond/Workspace/wave/x86_64-linux/cuda_env/build/cuda/install/device-cuda/runtime_build.gpr
object directory "/home/germond/Workspace/wave/x86_64-linux/cuda_env/build/cuda/install/device-cuda/obj" created for project Runtime_Build
library directory "/home/germond/Workspace/wave/x86_64-linux/cuda_env/build/cuda/install/device-cuda/adalib" created for project Runtime_Build
Changing to object directory of "Runtime_Build": "/home/germond/Workspace/wave/x86_64-linux/cuda_env/build/cuda/install/device-cuda/obj/"
/home/germond/Workspace/wave/x86_64-linux/gnat-llvm-ptx/install/bin/cuda-gcc -c -x ada -gnatA --RTS=/home/germond/Workspace/wave/x86_64-linux/cuda_env/build/cuda/install/device-cuda/ -gnatp -gnatg -nostdinc -fno-delete-null-pointer-checks -gnatp -gnatn2 -fcallgraph-info=su,da -ffunction-sections -fdata-sections -O2 -gnatec=/home/germond/Workspace/wave/x86_64-linux/cuda_env/tmp/GNAT-TEMP-000002.TMP -gnatem=/home/germond/Workspace/wave/x86_64-linux/cuda_env/tmp/GNAT-TEMP-000003.TMP /home/germond/Workspace/wave/x86_64-linux/cuda_env/build/cuda/install/device-cuda/gnat/machcode.ads`

**Comment by glacambre** [comment]
Oh, right, that makes perfect sense. Sorry for the noise 🤦.

**Comment by leogermond** [comment]
No worries, with the latest push it should now work automagically and be ready to get out of draft-jail after some testing :)

**Comment by QuentinOchem** [comment]
Since we now have a mechanism in setup.sh to generate bindings, let's close this PR.

**Pull request closed without merging**
