### PR TITLE
fix build errors

### PR DESCRIPTION
**Pull request by QuentinOchem**

### CODE REVIEW

**Review by glacambre — COMMENTED** [review]
I don't understand what this fixes - if it's the build issue we've been discussing on slack, why does this PR fix it? If your diagnosis is correct (missing cuda-gcc in $PATH), I'd expect a change in the dependencies of some of the Makefile's target.

**Comment by QuentinOchem** [comment]
> I don't understand what this fixes - if it's the build issue we've been discussing on slack, why does this PR fix it? If your diagnosis is correct (missing cuda-gcc in $PATH), I'd expect a change in the dependencies of some of the Makefile's target.

The makefile wasn't building cuda-gcc at all. Adding the FORCE target does fix that.

This then highlighted build errors that are also fixed by the PR.

**Comment by glacambre** [comment]
I see. For some reason I thought that targets that didn't specify anything on the right side of the colon would always be executed. I should probably go read a Makefile tutorial!

**Review by glacambre — APPROVED** [review]

**Comment by QuentinOchem** [comment]
> I see. For some reason I thought that targets that didn't specify anything on the right side of the colon would always be executed. I should probably go read a Makefile tutorial!

Hi had the exact same expectation.

**Pull request merged**
